#ifndef UEFI_SIMPLE_FILE_SYSTEM_PROTOCOL
#define UEFI_SIMPLE_FILE_SYSTEM_PROTOCOL

#include "uefi_base_types.h"
#include "uefi_file_protocol.h"

typedef struct _EFI_SIMPLE_FILE_SYSTEM_PROTOCOL EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;

#define EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_GUID \
	{0x0964e5b22, 0x6459, 0x11d2, \
	{0x8e, 0x39, 0x00, 0xa0, 0xc9, 0x69, 0x72, 0x3b}}

#define EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_REVISION 0x00010000

typedef EFI_STATUS (EFIAPI *EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME) (
		IN EFI_SIMPLE_FILE_SYSTEM_PROTOCOL *This,
		OUT EFI_FILE_PROTOCOL             **Root
		);

struct _EFI_SIMPLE_FILE_SYSTEM_PROTOCOL {
	UINT64                                      Revision;
	EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME OpenVolume;
};
#endif /* UEFI_SIMPLE_FILE_SYSTEM_PROTOCOL */
